function createfigure(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 14-Mar-2019 17:58:00

% Create figure
figure('InvertHardcopy','off','Color',[1 1 1]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create bar
bar(yvector1,...
    'FaceColor',[0.929411764705882 0.690196078431373 0.129411764705882]);

% Create title
title('Ranking of parameters based on \delta_{msqr} values','FontSize',11);

% Create ylabel
ylabel('\delta_{msqr}','FontSize',11);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 15]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 18]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','XTick',[1 2 3 4 5 6 7 8 9 10 11 12 13 14],...
    'XTickLabel',...
    {'\theta_{IPTG}','k_{IPTG}','k_{aTc}','\eta_{IPTG}','k^{P_{m0}}_L','\eta_{aTc}','\eta_{L}','k^{P_{m0}}_T ','\theta_{aTc} ','\eta_T','k^{p_m}_T ','sc_{Tmolec} ','sc_{Lmolec} ','k^{P_m}_L '});
